### ISSUE TITLE
OAuth2 tokens should not be stored in local storage

### ISSUE THREAD

**Issue by TimoBbz** [DSD-DBS/capella-collab-manager#107]
Currently, OAuth2 tokens are stored in local storage: It may allow XSS injections, or a user to make unwanted requests with its own token. More informations on the security issues with using local storage for tokens in this article: https://medium.com/@benjamin.botto/9536b0021321.

Storing the tokens in the backend session and implement the oauth routes in the backend should prevent the stealing of oauth tokens and the forgery of unwanted requests.

**Comment by MoritzWeber0** [comment]
We do already save the access token for Prometheus as cookie. If we decide to use cookies instead of the `localStorage`, we can reuse the code.

However, we are vulnerable to `CSRF` attacks when using cookies (which is probably less bad than XSS though). And the use of `CSRF` prevention tokens is a lot of implementation effort. 

But in principle I agree that we should better store the access token in a cookie.
