### ISSUE TITLE
Improve UI in project and model creation workflow

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-collab-manager#1110]
The UI elements are not consistently used in the project and tool model creation workflow. 

Some examples: 

![image](https://github.com/DSD-DBS/capella-collab-manager/assets/23395732/f722b6b5-914f-4151-be89-aa9885dd0675)
Here, the elements are aligned on the left side. The button is part of the mat-card. We decided to not have a "Cancel" button (navigation via breadcrumbs already provides this feature), so it should be removed.

![image](https://github.com/DSD-DBS/capella-collab-manager/assets/23395732/f0e62986-5372-49e4-b017-f759873fae5e)
This looks weird as it doesn't use the whole available screen space, but the buttons to add users are still on the right side. Also the "skip" should start with an uppercase character and looks weird in the full-width mat-card.

![image](https://github.com/DSD-DBS/capella-collab-manager/assets/23395732/c8fd68a0-dcfb-4d42-8d05-57cc40db2eeb)
The "Create model" button is on the left side, which is not consistent with the other button locations.
The "Skip model creation [...]" button has a different design again - it's placed in it's own mat-card, which is not full-width. The margins are not the same on the left & right side.

![image](https://github.com/DSD-DBS/capella-collab-manager/assets/23395732/86365587-5af3-418c-a9dd-786c3e4a71ab)
The model sources selection is centered in the middle (other components sticked to the left side).

**Comment by romeonicholas** [comment]
I'll share some updates with my justifications since I'm making up design choices as I go, in case there's anything anyone wants me to reconsider. 

**General Information Form Changes**
- Removed the Cancel button
- Left-aligned Create button
- Shortened the radio text. 
- Changed some HTML for accessibility (appropriate fieldsets and legends)

**General Information Questions**

- Can we shorten the radio text to "Public" and "Private" with an info hover (a user will only need to read the explanation once)
- Are we settled on "Internal"? (e.g. is it used that way throughout our projects?) I think "Internal" v "Private" doesn't communicate the difference very well
- I know the buttons aren't on the mat-card in other forms, but I think it actually needs to stay on the card for accessibility considerations, is that OK as long as I make it consistent throughout?

![Updated_ProjectCreation_GeneralInfo](https://github.com/DSD-DBS/capella-collab-manager/assets/79602065/7b377cfa-79fd-4262-8dc3-892285aaf993)

**Comment by MoritzWeber0** [comment]
> @MoritzWeber0 I'll share some updates with my justifications since I'm making up design choices as I go, in case there's anything anyone wants me to reconsider.
> 
> **General Information Form Changes**
> 
> * Removed the Cancel button

👍 

> * Left-aligned Create button

👍 

> * Shortened the radio text.

👍  (The new text is way clearer, I like it)

> * Changed some HTML for accessibility (appropriate fieldsets and legends)

👍 

> **General Information Questions**
> 
> * Can we shorten the radio text to "Public" and "Private" with an info hover (a user will only need to read the explanation once)

The terminology "Internal" is derived from Gitlab and some other services, which use a similar wording. 
"Internal" describes the state that all "logged in" users can see it, while "Public" described the state that all users (also not logged in users) can see the project. Therefore I would keep the name "Internal". We might also add a third visibility "Public" in the future. 

I'm also against the info hover - especially when the meaning isn't automatically apparent from the words.

> * Are we settled on "Internal"? (e.g. is it used that way throughout our projects?) I think "Internal" v "Private" doesn't communicate the difference very well

No, we are not. But Public is not an alternative as mentioned in the comment above. If you have other good ideas, feel free to share them.

> * I know the buttons aren't on the mat-card in other forms, but I think it actually needs to stay on the card for accessibility considerations, is that OK as long as I make it consistent throughout?

Yes, that's fine.

**Comment by romeonicholas** [comment]
**Project Member Changes**
- Fixed title margin
- Shifted add user and audit logs buttons into mat, added text
- Added sections to clarify form actions
- Changed skip/continue button into a link-styled button (because it takes the user to the next page, but has no impact on form)

**Project Member Questions**
- I just guessed on the log button text because the hover text was a little long and esoteric, but let me know if that should be more specific
- How often is the audit button currently used? I'd move it elsewhere if it's not a critical component (maybe "Project Information" metadata mat?)
- How many users does the average project have? The search bar seems unnecessary to me but obviously if projects get huge it must be useful

<img width="320" alt="Updated_ProjectMembers" src="https://github.com/DSD-DBS/capella-collab-manager/assets/79602065/aceab8f8-cbc5-42a8-bb71-6c7a1ae40bab">

**Comment by MoritzWeber0** [comment]
> OK, this is the bulk of the updates, I think I might be missing a few routes for T4C but they should look like the others once I'm finished. 
If there aren't any major call outs after sharing these with the team I'll start refactoring. [ProjectCreationUpdates.pdf](https://github.com/DSD-DBS/capella-collab-manager/files/13179424/ProjectCreationUpdates.pdf)

Looks really nice, love the comparison. Maybe you can put them as images in the PR description (once the PR is open), it's a little more accessible than a PDF that has to be downloaded first.
