### ISSUE TITLE
Jupyter: Pipe character is not working in the terminal of JupyterLab when using a macOS client standard keyboard for Germans (QWERTZ)

### ISSUE THREAD

**Issue by jamilraichouni** [DSD-DBS/capella-collab-manager#1654]
`opt + 7` (the Pipe character) cannot be entered in the JupyterLab Terminal.
In a notebook it works.

In the terminal it is kind of important as frequent terminal users know.
When I type the combination `opt + 7` I get:

<img width="490" alt="image" src="https://github.com/user-attachments/assets/4bf56c87-c7b9-463d-971b-a27e694784bd">

Doing the same (no matter if I take the left/ right `opt` key) I get the expected `|` character.

**Comment by jamilraichouni** [comment]
This is related to https://github.com/jupyterlab/jupyterlab/issues/11257 
Firefox cannot be tested. Tried Safari and there I get no reaction for `opt + 7` in the JupyterLab terminal.

**Comment by MoritzWeber0** [comment]
Hi @jamilraichouni,

I appreciate your effort with the investigation of the bug. However, it's mostly unrelated to this repository.
As you've already discovered, the bug originates in JupyterLab, therefore the bug also belongs the JupyterLab repository. Since we update Jupyter regularly, we benefit from the fix once it's released upstream.

To keep the list of issues clear, I'll close this issue. 

If there is anything we can do about it, e. g. with a custom configuration, feel free to reopen the issue.

Best,
Moritz
