### ISSUE TITLE
Create persistent volume claims per tool/version

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-collab-manager#298]
There has to be one persistent volume per (username, tool, version). Migration has to be possible (can be done manually). Capella workspaces depend on the version.
E.g. on instance xy, we'd like to keep the existing workspaces, but can manually rename the persistent volume claims in the cluster (to map them on the used Capella version).

Right now, the name is determined in `_get_claim_name` and is the username with some removed characters. If possible, we could add labels with tool and version and select the proper persistent volume by the labels. If not, we have to add the tool and version to the volume name (should be still human readable to allow the renaming).

**Comment by amolenaar** [comment]
I also looked into the alternative: one persistent volume with a workspace per tool. This requires slightly more work since we have to make `/workspace` customizable. It would have the advantage that users can move data from one tool to another, on the other hand we can not easily remove old data for unsupported tool versions.

**Comment by MoritzWeber0** [comment]
> It would have the advantage that users can move data from one tool to another.

When we have a new Capella version, users have to be able to move their models into the new workspace, otherwise migrations will not work properly (the upload feature doesn't have support for large files yet).
