### ISSUE TITLE
Review and change response codes in code with Gitlab API calls

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-collab-manager#668]
I would reserve 500 for situations we did not anticipate. It's not a fault in the backend service that the status badge can't be loaded. In the end it's a user error. The backend handles it, it does not fail in an unforeseen way (e.i. 500).

_Originally posted by @amolenaar in https://github.com/DSD-DBS/capella-collab-manager/pull/665#discussion_r1154598380_
            
This applies to all endpoints which use a connection to Git/Gitlab.

**Comment by amolenaar** [comment]
I think a couple of 4xx codes can be used instead of 500 (Internal Server Error).
Status code 500 ius reserved for [_unexpected_ errorous conditions](https://www.rfc-editor.org/rfc/rfc9110.html#name-500-internal-server-error).
The situations we encounter (expired credentials, invalid urls (= user input), etc.) are situations we anticipate. Situations a client can remedy. Hence we should return 4xx error codes.

* 403: You can try, but you do not have access
* 404: ([Not Found](https://www.rfc-editor.org/rfc/rfc9110.html#name-404-not-found)) - If a resource cannot  be found. Can also be used if a resource can not be found downstream.
* 409: ([Conflict](https://www.rfc-editor.org/rfc/rfc9110.html#name-409-conflict)) - Is appropriate IMHO, since the request cannot be fulfilled due to a conflict with the actual state of the system.
* 422: (Unprocessable Content](https://www.rfc-editor.org/rfc/rfc9110.html#name-422-unprocessable-content)  When we somehow cannot fulfill a user request (e.g. due to a "broken" downstream system).
