### ISSUE TITLE
Collaborate on Jupyter notebooks

### ISSUE THREAD

**Issue by amolenaar** [DSD-DBS/capella-collab-manager#678]
Currently users can have individual notebook instances. It would be great if we can allow notebooks on _project_ level. That would make it easier for users to share notebooks and scripts.

For this to work, we need to be able to import (Capella) models in the shared notebook environment.

**Open Questions**

* Can and should we differentiate between users in the notebook environment? It would make it easier to see who changed what.
* How do we decide which models to load in the shared notebook environment?
* Are there any security risks involved?

**Comment by MoritzWeber0** [comment]
Instead of creating a shared persistent volume claim for each project, I'd use a more "explicit" approach. As we already have the infrastructure for toolmodels within projects and "Jupyter" can also be selected as tool, I'd prefer this approach:

- To create a shared volume, a model with the tool "Jupyter" in a project has to be created. During creation, the PVC is created.
- If the user has access to the project with `read-only` permission, the PVC is mounted as read-only volume in Jupyter sessions. 
- If the user has access to the project with `write` permission, the PVC is mounted as read/write volume in Jupyter sessions. 
- When the model is deleted, the PVC is also deleted.

Also, it could benefit from workspace automation in the future, e.g. to run regular/nightly backups of the Jupyter notebooks to a linked Git repository (like we have to for TeamForCapella).
