### ISSUE TITLE
Monitor session connectivity health

### ISSUE THREAD

**Issue by vik378** [DSD-DBS/capella-collab-manager#72]
Some users report that Guacamole session is freezing or resets completely. This is most likely related to connectivity issues, however it is difficult to tell if this is a user connectivity issue (like when working on a train WiFi) or an infrastructural one. 

To determine connectivity issues affecting the platform it would be useful to somehow detect / measure those outages per sessions and expose as an OpenMetric (maybe like number of sessions that experienced connectivity issues within last minute / number of sessions). A high value would indicate that the platform is affected (by some sort of bandwidth limitation) while a low value will indicate that some users are affected.

**Comment by MoritzWeber0** [comment]
Session stability has improved significantly over the past year, as has connectivity. Most of the service requests can be traced back to a bad internet connection. Therefore, I'd like to close this ticket due to low relevance and to keep track of open tickets. Feel free to reopen it when it becomes relevant again. 

https://github.com/DSD-DBS/capella-collab-manager/issues/6 may also improve the situation, so I'd rather focus on implementing direct RDP access.
