### ISSUE TITLE
Add training capabilities

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-collab-manager#848]
A "training" mode would be a great benefit. There should be a selection of different trainings. 

Trainings can require sessions, which can pre-configured (e.g. loading of specific models into a Capella workspace).

**Comment by Paula-Kli** [comment]
in short - its about maximizing design useful tool space

1. There is no need for header / nav in that mode
2. There is no need for footer in that mode
3. it should be possible to re-balance ratio between the notebook and the capella session
4. it should be possible to maximize jupyter session
5. it should be possible to collapse jupyter session so that capella session takes entire screen but also a tiny uncollapse button remains on the jupyter side (focus mode)
 -> when one side is collapsed it can remain as a tiny side bar with an "uncollapse" button, while the fullscreen thingy should make that panel fullscreen. In fact what we need is ability to make a panel full-screen and get back from that mode to a split-screen mode, what UI means we use for that is really up to you 
7.  and 7 - same as above for capella session
8. oh and there is no need for the panels to be dragged around

then another pretty big thing will be about initialization - we will start a training activity, not a session - and that involves spinning up sessions, getting some initial stuff into workspaces and maybe pre-opening things 

also no need for more than two open sessions at a time

**Comment by Paula-Kli** [comment]
![MicrosoftTeams-image](https://github.com/DSD-DBS/capella-collab-manager/assets/49535291/230fb733-1d9c-4f72-8f1a-edb7d948a90d)

**Comment by MoritzWeber0** [comment]
Issue was split into smaller work packages, available here: https://github.com/DSD-DBS/capella-collab-manager/milestone/8
