### ISSUE TITLE
Cache diagram cache from Github

### ISSUE THREAD

**Issue by Paula-Kli** [DSD-DBS/capella-collab-manager#893]
Artifacts can only be downloaded as a whole zip file at once. At the moment the zip file is downloaded completely for the index, then thrown away and dowloaded again for each single file in the diagram cache. That should be cached to minimize the requests and speed up the whole loading process of the diagram cache (possibly using redis(?))

**Comment by dominik003** [comment]
@MoritzWeber0 and I decided to implement this as follows:

- We store the unique repository identifier (project ID on GitLab and `owner/repository` on GitHub) in the database git model since there is a one-to-one relationship. The current plan is to set this id the first time we need it, but in the future we may be able to set it directly during model creation. It is important to reset the repository id, i.e. set it to `None`, when the repository path is updated.
